version: '3.8'

services:
  webide-react-fe:
    image: 46112/webide-react-fe:latest
    container_name: webide-react-fe
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webide-network

networks:
  webide-network:
    driver: bridge 